# Change these first
owner: MiAguila 
repo: uptime

sites:
  - name: Orders production
    url: https://orders.api.katapultcommerce.com/api/health/
  - name: Orders Api Tiendas 3B
    url: https://orders.api.t3b.katapultcommerce.com/api/health/
#  - name: Orders Api Tiendas on247
#    url: https://orders.api.on247.katapultcommerce.com/api/health/
  - name: metrics
    url: https://metrics.api.katapultcommerce.com/api/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.katapultcommerce.com
  # baseUrl: /your-repo-name
  logoUrl: https://media-exp2.licdn.com/dms/image/C560BAQG0w85tovXNDw/company-logo_200_200/0/1652748232832?e=1663200000&v=beta&t=DqF-eoJkRC69MaeTKgVcReyx79X6vh3FtQjYxQwYwYM
  name: Katapult Commerce Uptime Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
 
 workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
